### ISSUE TITLE
Caller cannot specify a network for deployContract and callContract on the EthereumWallet

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-js-sdk#4]
## Problem

A caller of `deployContract` or `callContract` (both functions on the EthereumWallet) currently **cannot** specify the network (mainnet, ropsten, etc) on which the action should be performed.

https://github.com/comit-network/comit-js-sdk/blob/e8d0fc499af3614cb350776ebc60a4494e38bb64/src/ethereumWallet.ts#L23-L39

This can be dangerous because funds could accidentally be sent on the wrong network, i.e.: the wallet is connected to a Mainnet node but the application would actually like to interact with a ropsten node

## Goal

Make sure the network is not implicit so that the application has to actively specify it.

## Recommendation

We should add a `chainId` parameter to these methods and assert that the underlying `Web3` client is actually connected to a network with that chainId.

**Comment by bonomat** [comment]
I think this better solved by initializing the wallet with a `chain_id` and then initialize the `TransactionRequest` with this `chain_id`. As the `chain_id` is part of the signature, sending a transaction to a wrongly connected network will fail, i.e. the network will reject that transaction.

@thomaseizinger : what do you think? If so, we can solve it together with #154 , e.g. change the constructor of the `EthereumWallet` to accept the provider

```
const web3 = new Web3(url, chain_id) // (or Ethers.js)
const wallet = new EthereumWallet(
  web3Provider: web3.currentProvider
);
```

and then on each call we can do: 

```
public async deployContract(
    data: string,
    amount: BigNumber,
    gasLimit: string
  ): Promise<string> {
    const value = new BigNumberEthers(amount.toString());
    const transaction: TransactionRequest = {
      data,
      value,
      gasLimit
	  chain_id: this.provider.getNetwork()
    };
    return this.sendTransaction(transaction);
  }
```

**Comment by thomaseizinger** [comment]
That doesn't solve the problem unfortunately. If `cnd` returns you an action that is meant to be executed on a chain with id `3` and your wallet is connected to chain `1`, it will still happily sign and broadcast it.

We need to pass the `chainId` in the action method to prevent these kind of errors from happening :)

This issue really describes a shortcoming of the current Ethereum wallet interface. `cnd` already returns this information and we should make use of it. Alternatively, we can discuss whether the overall approach is viable but then we should change all the actions (ethereum, bitcoin and lightning) to not return the network/chain but implicitly refer to whatever `cnd` is connected to. However, it is the first time that I hear about a proposal to do this differently? I thought we had consensus on being explicit here :thinking:

**Comment by bonomat** [comment]
Fair enough :) Then this ticket is orthogonal to the other one and we need to do both.
We have this field already on the function of `BitcoinWallet` so adding it to `EthereumWallet` would make it symmetrical. 

Now that you mention it: I'm wondering how a dev/user should get the network/chain_id from to initialize wallets in the first place in a usable and non-redundant way 🤔

Maybe cnd should provide an endpoint to return this information so that the sdk can learn that from there... but that's a different story. 

Let's keep this ticket as is.

**Comment by thomaseizinger** [comment]
> Maybe cnd should provide an endpoint to return this information so that the sdk can learn that from there... but that's a different story.

My take on this would be that the application should be the source of truth, i.e. have a drop-down menu or something where you select which chains you want to target. `cnd` should be configured accordingly to that. Likely, the user's intent is better captured in the application than in their configuration of cnd. Depending on the usecase, the application configures cnd to make sure things don't get out of sync :)

> but that's a different story.

!

**Comment by bonomat** [comment]
@D4nte / @thomaseizinger 

I just wanted to do this ticket and noticed that the payload definitions for ethereum still use `network`:

https://github.com/comit-network/comit-js-sdk/blob/c36d344dde50cf42e6c77f0a26bc4a91abb8d04d/src/cnd/action_payload.ts#L17-L22

It seems like we never update this to use `chain_id`. Does this mean this sdk version is/was not compatible with our current cnd version or am I missing something? 
It's not a problem as we never used the `network` field apparently.

**Comment by thomaseizinger** [comment]
> @D4nte / @thomaseizinger
> 
> I just wanted to do this ticket and noticed that the payload definitions for ethereum still use `network`:
> 
> https://github.com/comit-network/comit-js-sdk/blob/c36d344dde50cf42e6c77f0a26bc4a91abb8d04d/src/cnd/action_payload.ts#L17-L22
> 
> It seems like we never update this to use `chain_id`. Does this mean this sdk version is/was not compatible with our current cnd version or am I missing something?
> It's not a problem as we never used the `network` field apparently.

I think it is because we never use it, feel free to change it as part of doing this ticket.
